name: Cart CICD
run-name: Cart CICD
on: [push]
jobs:
  ci:
    uses: VenkatBheemireddyOrg/github-reusable-actions/.github/workflows/ci.yml@main
    with:
      component: cart
      appType: nodejs
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}

  deploy:
    needs: ci
    uses: VenkatBheemireddyOrg/github-reusable-actions/.github/workflows/deploy.yml@main
    with:
      component: cart






